# Generated by Django 4.1.5 on 2023-01-19 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Via',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_via', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('posologia', models.CharField(max_length=30)),
                ('via', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receita.via')),
            ],
        ),
    ]
