# Generated by Django 3.2.16 on 2023-02-01 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='quantidade',
            field=models.CharField(default='------ 01 CAIXA', max_length=150),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='posologia',
            field=models.CharField(max_length=150),
        ),
    ]
